double r, p, n1, n2, n3;
Console.WriteLine("Digite o primeiro número: ");
n1 = double.Parse(Console.ReadLine());
Console.WriteLine("Digite o segundo número: ");
n2 = double.Parse(Console.ReadLine());
Console.WriteLine("Digite o terceiro número: ");
n3 = double.Parse(Console.ReadLine());
r = n1 + n2 + n3;
p = Math.Pow(r, 2);
Console.WriteLine("O resultado da potência é: " + p);