using System.Drawing;

string n1, n2, n3;
int q1, q2, q3;
double v1, v2, v3, vp1, vp2, vp3, vt;
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("digite o nome do 1º produto");
n1 = Console.ReadLine();
Console.WriteLine("digite o nome do 2º produto");
n2 = Console.ReadLine();
Console.WriteLine("digite o nome do 3º produto");
n3 = Console.ReadLine();
Console.WriteLine("digite a quantidade do 1º produto");
q1 = int.Parse (Console.ReadLine());
Console.WriteLine("digite a quantidade do 2º produto");
q2 = int.Parse(Console.ReadLine());
Console.WriteLine("digite a quantidade do 3º produto");
q3 = int.Parse(Console.ReadLine());
Console.WriteLine("digite o valor do 1º produto");
v1 = double.Parse(Console.ReadLine());
Console.WriteLine("digite o valor do 2º produto");
v2 = double.Parse(Console.ReadLine());
Console.WriteLine("digite o valor do 3º produto");
v3 = double.Parse(Console.ReadLine());
vp1 = v1 * q1;
vp2 = v2 * q2;
vp3 = v3 * q3;
vt = vp1 +  vp2 + vp3;
Console.WriteLine("O valor total de " + n1 + " é " + vp1);
Console.WriteLine("O valor total de " + n2 + " é " + vp2);
Console.WriteLine("O valor total de " + n3 + " é " + vp3); 
Console.WriteLine("O valor total da compra é " + vt);