algoritmo "4 equações"
// Função :
// Autor :
// Data : 04/03/2026
// Seção de Declarações
var
   sub, soma, divi, mult, numero1, numero2: real
inicio
escreva ("Digite o primeiro número: ")
leia(numero1)
Escreva("Digite o segundo número: ")
Leia(numero2)
soma <- numero1 + numero2
Escreval("O resultado da soma é: ",  soma)
sub <- numero1 - numero2
Escreval("O resultado da subtração é: ",  sub)
mult <- numero1 * numero2
Escreval("O resultado da multiplicação é: ",  mult)
divi <- numero1 / numero2
Escreval("O resultado da divisão é: ",  divi)
fimalgoritmo
