algoritmo "Maior/menor/igual"
// Função :
// Autor :
// Data : 25/03/2026
// Seção de Declarações
var
     n1, n2, r: real
inicio
escreva("Digite o primeiro número: ")
      leia (n1)
           escreva("Digite o segundo número: ")
                      leia (n2)
                r <- (n1 + n2)
      escreva ("o resultado é:", r)
se (r > 30) entao
      escreva (" adição maior que 30")
      senao
      se (r = 30) entao
      escreva (" adição igual a 30")
      senao
      se (r < 30)
escreva (" adição menor que 30")
      fimse
      fimse
      fimse
fimalgoritmo
