algoritmo "Tabela médica"
// Função :
// Autor :
// Data : 11/03/2026
// Seção de Declarações
var
   a, h, m : Real
   n : caracter
inicio
      escreva ("digite o nome: ")
      leia (n)
      escreva ("digite o peso: ")
      leia (a)
      se
      h <-(72.7*altura)-58
      escreva ("Segundo a tabela médica, o peso ideal é: ", h)
      senao
      m <-(62.1*altura)-44.7
      escreva ("Segundo a tabela médica, o peso ideal é: ", m)
fimalgoritmo
